-- Default task template, edited later from Admin > Task template. Default owner: Greg.
INSERT INTO task_templates (id, parent_id, name, phase, sort_order, default_needed, applies_when, gate, ref_label, default_owner_id) VALUES
    (1, NULL, 'Contract signed', 'pre_install', 10, 1, 'all', 'start_clock', NULL, (SELECT id FROM users WHERE email = 'person@example.com')),
    (2, NULL, 'Design', 'pre_install', 20, 1, 'all', NULL, NULL, (SELECT id FROM users WHERE email = 'person@example.com')),
    (3, 2, 'Planset sent', 'pre_install', 10, 1, 'all', NULL, NULL, NULL),
    (4, 2, 'Planset received', 'pre_install', 20, 1, 'all', NULL, NULL, NULL),
    (5, 2, 'Engineering stamp received', 'pre_install', 30, 1, 'all', NULL, NULL, NULL),
    (6, NULL, 'Zoning permit', 'pre_install', 30, 1, 'all', NULL, 'Permit #', (SELECT id FROM users WHERE email = 'person@example.com')),
    (7, 6, 'Applied', 'pre_install', 10, 1, 'all', NULL, NULL, NULL),
    (8, 6, 'Received', 'pre_install', 20, 1, 'all', NULL, NULL, NULL),
    (9, NULL, 'Building permit', 'pre_install', 40, 1, 'all', NULL, 'Permit #', (SELECT id FROM users WHERE email = 'person@example.com')),
    (10, 9, 'Applied', 'pre_install', 10, 1, 'all', NULL, NULL, NULL),
    (11, 9, 'Received', 'pre_install', 20, 1, 'all', 'install_prereq', NULL, NULL),
    (12, NULL, 'Interconnection', 'pre_install', 50, 1, 'all', NULL, 'Work order #', (SELECT id FROM users WHERE email = 'person@example.com')),
    (13, 12, 'Applied (app and fee)', 'pre_install', 10, 1, 'all', NULL, NULL, NULL),
    (14, 12, 'Conditional approval', 'pre_install', 20, 1, 'all', 'install_prereq', NULL, NULL),
    (15, 12, 'Approved / permission to install', 'pre_install', 30, 1, 'all', 'install_prereq', NULL, NULL),
    (16, NULL, 'Utility upgrade', 'pre_install', 60, NULL, 'all', NULL, 'Work order #', (SELECT id FROM users WHERE email = 'person@example.com')),
    (17, 16, 'Invoice received', 'pre_install', 10, 1, 'all', NULL, NULL, NULL),
    (18, 16, 'Invoice paid (by customer)', 'pre_install', 20, 1, 'all', NULL, NULL, NULL),
    (19, 16, 'Upgrade completed', 'pre_install', 30, 1, 'all', NULL, NULL, NULL),
    (20, NULL, 'Materials', 'pre_install', 70, 1, 'all', NULL, NULL, (SELECT id FROM users WHERE email = 'person@example.com')),
    (21, 20, 'Panels', 'pre_install', 10, 1, 'pv', NULL, NULL, NULL),
    (22, 20, 'Inverters', 'pre_install', 20, 1, 'all', NULL, NULL, NULL),
    (23, 20, 'Racking / tracker', 'pre_install', 30, 1, 'pv', NULL, NULL, NULL),
    (24, 20, 'Batteries', 'pre_install', 40, 1, 'storage', NULL, NULL, NULL),
    (25, 20, 'BOS', 'pre_install', 50, 1, 'all', NULL, NULL, NULL),
    (26, NULL, 'Installation', 'installation', 10, 1, 'all', NULL, NULL, (SELECT id FROM users WHERE email = 'person@example.com')),
    (27, 26, 'Started', 'installation', 10, 1, 'all', 'install_started', NULL, NULL),
    (28, 26, 'Completed', 'installation', 20, 1, 'all', NULL, NULL, NULL),
    (29, NULL, 'Third-party sitework', 'installation', 20, 0, 'all', NULL, NULL, (SELECT id FROM users WHERE email = 'person@example.com')),
    (30, NULL, 'Commissioning', 'installation', 30, 1, 'all', NULL, NULL, (SELECT id FROM users WHERE email = 'person@example.com')),
    (31, 30, 'Inverters configured (grid profile)', 'installation', 10, 1, 'all', NULL, NULL, NULL),
    (32, 30, 'Batteries commissioned', 'installation', 20, 1, 'storage', NULL, NULL, NULL),
    (33, NULL, 'Monitoring portal', 'installation', 40, 1, 'all', NULL, NULL, (SELECT id FROM users WHERE email = 'person@example.com')),
    (34, 33, 'Inverters online', 'installation', 10, 1, 'all', NULL, NULL, NULL),
    (35, 33, 'Site created in portal', 'installation', 20, 1, 'all', NULL, NULL, NULL),
    (36, 33, 'Map / layout created', 'installation', 30, 1, 'all', NULL, NULL, NULL),
    (37, 33, 'All strings / panels validated', 'installation', 40, 1, 'all', NULL, NULL, NULL),
    (38, 33, 'Customer access granted', 'installation', 50, 1, 'all', NULL, NULL, NULL),
    (39, NULL, 'Final inspection', 'installation', 50, 1, 'all', NULL, 'Permit #', (SELECT id FROM users WHERE email = 'person@example.com')),
    (40, NULL, 'Utility', 'installation', 60, 1, 'all', NULL, NULL, (SELECT id FROM users WHERE email = 'person@example.com')),
    (41, 40, 'COC submitted', 'installation', 10, 1, 'all', NULL, NULL, NULL),
    (42, 40, 'Meter swap / DER visit', 'installation', 20, 1, 'all', NULL, NULL, NULL),
    (43, 40, 'PTO received', 'installation', 30, 1, 'all', 'pto', NULL, NULL),
    (44, NULL, 'SREC registration', 'closeout', 10, 1, 'pv', NULL, NULL, (SELECT id FROM users WHERE email = 'person@example.com')),
    (45, NULL, 'SolarEdge extended warranty', 'closeout', 20, NULL, 'all', NULL, NULL, (SELECT id FROM users WHERE email = 'person@example.com')),
    (46, NULL, 'SolarInsure registration', 'closeout', 30, NULL, 'all', NULL, NULL, (SELECT id FROM users WHERE email = 'person@example.com')),
    (47, NULL, 'Utility rebate', 'closeout', 40, NULL, 'all', NULL, NULL, (SELECT id FROM users WHERE email = 'person@example.com')),
    (48, 47, 'Paperwork gathered', 'closeout', 10, 1, 'all', NULL, NULL, NULL),
    (49, 47, 'Submitted to utility', 'closeout', 20, 1, 'all', NULL, NULL, NULL),
    (50, NULL, 'Virtual net metering', 'closeout', 50, NULL, 'all', NULL, NULL, (SELECT id FROM users WHERE email = 'person@example.com')),
    (51, NULL, 'Photos', 'closeout', 60, 1, 'all', NULL, NULL, (SELECT id FROM users WHERE email = 'person@example.com')),
    (52, 51, 'Module photos', 'closeout', 10, 1, 'pv', NULL, NULL, NULL),
    (53, 51, 'Inverter photos', 'closeout', 20, 1, 'all', NULL, NULL, NULL),
    (54, 51, 'Drone / marketing photos', 'closeout', 30, 1, 'all', NULL, NULL, NULL),
    (55, NULL, 'Deposit received', 'payments', 10, 1, 'all', NULL, NULL, (SELECT id FROM users WHERE email = 'person@example.com')),
    (56, NULL, 'Install payment received', 'payments', 20, 1, 'all', NULL, NULL, (SELECT id FROM users WHERE email = 'person@example.com')),
    (57, NULL, 'Final payment received', 'payments', 30, 1, 'all', NULL, NULL, (SELECT id FROM users WHERE email = 'person@example.com'));
