expose_php = Off
date.timezone = America/New_York
display_errors = Off
log_errors = On
error_log = /dev/stderr
memory_limit = 256M
upload_max_filesize = 20M
post_max_size = 25M

session.use_strict_mode = 1
session.use_only_cookies = 1
session.cookie_httponly = 1
session.cookie_samesite = Lax
session.gc_maxlifetime = 86400
